import Head from "next/head";
import LaunchList from "../components/launch-list";
import LaunchHeader from "../components/launch-header";


export default function Home({ past, next }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <LaunchHeader next={next} />
        <hr/>
        <LaunchList past={past} />
      </div>
    </div>
  );
}

// getting next and past launches
export async function getServerSideProps() {
  const res = await fetch(`https://api.spacexdata.com/v3/launches/past`);
  const res2 = await fetch(`https://api.spacexdata.com/v3/launches/next`);
  const past = await res.json();
  const next = await res2.json();
  return { props: { past, next } };
}
